### ISSUE TITLE
Invalid VDD/VSS port shapes in LEF

### ISSUE THREAD

**Issue by tajayi** [bespoke-silicon-group/bsg_fakeram#3]
On successful generation, the LEF file has several VSS and VDD pins. This errors out in OpenROAD and commercial tools. Usually, the LEF file should have a single unique PIN with multiple shapes (i.e RECTs) underneath the PORT.

For example
```
  PIN VSS
    DIRECTION INOUT ;
    USE GROUND ;
    PORT
      LAYER metal4 ;
      RECT 2.056 47.373 14.390 47.633 ;
      RECT 2.056 3.173 14.390 3.433 ;
      RECT 2.056 1.873 14.390 2.133 ;
      END
    END VSS
```

**Comment by stdavids** [comment]
Thanks Tutu! Always appreciate the feedback :)

This has been fixed in commit 5ca74579ef065368e80d2e780a3f0a404485d65f. I don't really have any infrastructure to test this with the commercial cad tools that you are using (it worked with ours haha). Please re-open this issue if it still doesn't work. For OpenROAD, I believe there are still more issues that need to be resolved before we can test it there.

**Comment by taylor-bsg** [comment]
Maybe for the record, we can write here in the thread which commercial
tools and versions we tried?

**Comment by stdavids** [comment]
ICC2LM version O-2018.06-SP5

**Comment by tajayi** [comment]
Cadence Innovus v15.21-s080_1

**Comment by taylor-bsg** [comment]
TY!
